-- MySQL Script generated by MySQL Workbench
-- Mon Feb 14 15:06:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Company
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Company
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Company` DEFAULT CHARACTER SET utf8 ;
USE `Company` ;

-- -----------------------------------------------------
-- Table `Company`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Company`.`Company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `cash` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Company`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Company`.`Person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Company`.`Person_Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Company`.`Person_Company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  `salary` FLOAT NOT NULL,
  `active` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `company_id_idx` (`company_id` ASC),
  INDEX `person_id_idx` (`person_id` ASC),
  CONSTRAINT `company_id`
    FOREIGN KEY (`company_id`)
    REFERENCES `Company`.`Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `Company`.`Person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Company`.`Account_Receivable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Company`.`Account_Receivable` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  `amount` FLOAT NOT NULL COMMENT '\n',
  `due_date` DATE NOT NULL,
  `to_company_id` INT NOT NULL,
  `from_company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `to_company_id_idx` (`to_company_id` ASC),
  INDEX `from_company_id_idx` (`from_company_id` ASC),
  CONSTRAINT `to_company_id`
    FOREIGN KEY (`to_company_id`)
    REFERENCES `Company`.`Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `from_company_id`
    FOREIGN KEY (`from_company_id`)
    REFERENCES `Company`.`Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Company`.`Account_Payable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Company`.`Account_Payable` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NOT NULL,
  `amount` FLOAT NOT NULL,
  `due_date` DATE NOT NULL,
  `priority` FLOAT NOT NULL,
  `to_company_id` INT NOT NULL,
  `from_company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `to_icompany_id_idx` (`to_company_id` ASC),
  INDEX `from_company_id_account_payable_idx` (`from_company_id` ASC),
  CONSTRAINT `to_company_id_account_payable`
    FOREIGN KEY (`to_company_id`)
    REFERENCES `Company`.`Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `from_company_id_account_payable`
    FOREIGN KEY (`from_company_id`)
    REFERENCES `Company`.`Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
